# Generated by Django 4.0.3 on 2022-05-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('basicclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basicclass')),
                ('date', models.DateField()),
                ('morng_presence', models.BooleanField(default=True)),
                ('aftrn_presence', models.BooleanField(default=True)),
            ],
            bases=('home.basicclass',),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_year', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchClass',
            fields=[
                ('basicclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basicclass')),
                ('class_name', models.CharField(max_length=255)),
                ('class_section', models.CharField(max_length=255)),
            ],
            bases=('home.basicclass',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('basicclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basicclass')),
                ('subject_name', models.CharField(max_length=255)),
            ],
            bases=('home.basicclass',),
        ),
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('basicclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basicclass')),
                ('batch_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batch')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batchclass')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            bases=('home.basicclass',),
        ),
    ]
