# Generated by Django 4.0.3 on 2022-05-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherallocation',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_name',)},
        ),
        migrations.AddField(
            model_name='batchclass',
            name='batch_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batch'),
        ),
        migrations.AddField(
            model_name='batchclass',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batchclass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together={('batch_year', 'class_name', 'subject_name')},
        ),
        migrations.AlterUniqueTogether(
            name='batchclass',
            unique_together={('batch_year', 'class_name', 'class_section', 'class_teacher')},
        ),
    ]
