# Generated by Django 4.0.3 on 2022-05-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('basicclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basicclass')),
                ('time_table_file', models.FileField(blank=True, null=True, upload_to='timeTables')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batchclass')),
            ],
            bases=('home.basicclass',),
        ),
    ]
